defaults:
  - constraint_parser@model: constraint_parser_roberta
  - torch_dataset@train_dataset: basic_dataset
  - torch_dataset@dev_dataset: real_synth_table_dataset
  - evaluator: constraint_parser_roberta_evaluator
  - _self_

train_dataset:
  data:
    filepath: data/processed_ad/train_unfiltered.json
    heauristic_filter: false
    filter_with_goal: false

dev_dataset:
  real_data:
    filepath: data/processed_ad/dev_unfiltered.json
    heauristic_filter: false
    filter_with_goal: false
  max_retries: 500
  original_prob: 0.05
  verbose: false

model:
  checkpoint_path: outputs/constraint_parse_test/model.pkl

evaluator:
  k: 1

train:
  save_checkpoint_dir: outputs/constraint_parse_test2/
  optim_state_path: null
  epochs: 1000
  dataloader_workers: 0
  bsize: 2
  grad_accum_steps: 18
  log_every: 256
  eval_every: 1024
  save_every: 16384
  eval_bsize: 2
  eval_batches: 16
  lr: 1e-4
  roberta_lr: 1e-5
  weight_decay: 0.01
  max_steps: null
  loss: {}

wandb:
  use_wandb: true
  wandb_project: constraint_parse_train_roberta
  log_name: null

